import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./context/assessments.context";
import { QportalProvider } from "./context/qportal.context";
import { ResultProvider } from "./context/Result.context";
import { HistoryProvider } from "./context/history.context";
import { AssessmentProvider } from "./context/admin.context";
import { AdminResultProvider } from './context/adminResult.context';
import { ManageAssessmentProvider } from './context/manageAssessment.context';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QportalProvider>
          <AppProvider>
            <ResultProvider>
              <HistoryProvider>
                <AssessmentProvider>
                  <AdminResultProvider>
                    <ManageAssessmentProvider>
                      {children}
                    </ManageAssessmentProvider>
                  </AdminResultProvider>
                </AssessmentProvider>
              </HistoryProvider>
            </ResultProvider>
          </AppProvider>
        </QportalProvider>
      </body>
    </html>
  );
}
